qiniu:
  accesskey: WQMytg9Nn2ictSU3o4_Lf3Z68lM0IWeUiT3QFTWE
  secretKey: J0elk9usrfqYZeoFFGgGRgRUAwFhvd4fWn0oBidy
  bucket: matchbox
  path: http://prv0aejgs.bkt.clouddn.com

server:
  tomcat:
    uri-encoding: UTF-8
  port: 49521
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        event:
          merge:
            entity_copy_observer: allow

  datasource:
    url: jdbc:postgresql://rainkq.tk:5432/matchbox?useSSl=false&useunicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "postgres"

  redis:
    database: 0
    host: rainkq.tk
    port: 6699
    password: "h0ldingy@u"


  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  cache:
    redis:
      time-to-live: 600000





